'use strict';

const assert = require('node:assert/strict');
const crypto = require('node:crypto');
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');
const test = require('node:test');

const { deriveRegistry, writeOrCheck } = require('../tools/generate-capability-registry.cjs');

function writeJson(root, relative, value) {
  const target = path.join(root, relative);
  fs.mkdirSync(path.dirname(target), { recursive: true });
  fs.writeFileSync(target, JSON.stringify(value, null, 2) + '\n');
}

function fixture() {
  const root = fs.mkdtempSync(path.join(os.tmpdir(), 'axm-hub-cap-'));
  const catalogGame = {
    id: '001-test-game', slot: '001', name: 'Test Game', status: 'WORKING TEST', version: '1.0.0',
    minPlayers: 1, maxPlayers: 2,
  };
  writeJson(root, 'catalog.json', {
    schema: 'axm.local-game-catalog/v1',
    distribution: { id: 'axm-local-game-hub', name: 'AXM Local Game Hub', version: 'test', status: 'EXPERIMENTAL' },
    policy: { internetRequired: false, accountRequired: false, telemetry: false, activeGameLimit: 1, qrControllers: true },
    games: [catalogGame],
  });
  writeJson(root, 'games/001-test-game/game.manifest.json', {
    slot: '001', game_id: '001-test-game', name: 'Test Game', status: 'WORKING TEST', version: '1.0.0',
    min_players: 1, max_players: 2,
    allowed_seat_types: ['human', 'adapter'],
    launch: { start_command: 'managed-by-game-hub', local_only_default: true },
    join: { supports_qr: true, supports_lan_link: true, supports_room_code: true },
    controls: {
      phone_controller: true, keyboard: true, mouse: false, touch: true, shared_screen: true,
      intent_protocol: 'axm-semantic-input-v1', adapter_observation: 'axm-seat-screen-semantics-v1',
    },
    session: { passes_seat_map: true, returns_result_summary: true, drop_in_out_later: false },
    rules: { local_authoritative_state: true, clients_send_input_intentions: true },
    verification: { game_night: { disconnect_recovery: 'verified', adapter_state_interface: 'verified', blocking_overlay_escape: 'pending' } },
  });
  return root;
}

function rowById(result, id) {
  return result.rows.find(row => row.id === id);
}

test('derives provider and external-consumer capability edges from exact source state', () => {
  const root = fixture();
  const result = deriveRegistry(root);
  assert.deepEqual(rowById(result, 'game.join.lan-link').providers, ['001-test-game']);
  assert.deepEqual(rowById(result, 'game-hub.offline-after-download').providers, ['axm-local-game-hub']);
  assert.deepEqual(rowById(result, 'game.seat.adapter-state-interface').providers, ['001-test-game']);
  assert.deepEqual(rowById(result, 'axm-semantic-input-v1').consumers, ['001-test-game']);
  assert.deepEqual(rowById(result, 'axm-seat-screen-semantics-v1').consumers, ['001-test-game']);
  assert.equal(rowById(result, 'axm-semantic-input-v1').truth.declaration_is_runtime_proof, false);
});

test('registry and receipt are deterministic and receipt binds exact output bytes', () => {
  const root = fixture();
  const first = deriveRegistry(root);
  const second = deriveRegistry(root);
  assert.equal(first.registryText, second.registryText);
  assert.equal(first.receiptText, second.receiptText);
  const digest = crypto.createHash('sha256').update(first.registryText).digest('hex');
  assert.equal(first.receipt.output.sha256, digest);
  assert.equal(first.receipt.output.records, first.rows.length);
});

test('source binding fails closed when catalog and manifest identity drift', () => {
  const root = fixture();
  const manifestPath = path.join(root, 'games/001-test-game/game.manifest.json');
  const manifest = JSON.parse(fs.readFileSync(manifestPath, 'utf8'));
  manifest.version = '2.0.0-drift';
  fs.writeFileSync(manifestPath, JSON.stringify(manifest, null, 2) + '\n');
  assert.throws(() => deriveRegistry(root), /version does not match catalog/);
});

test('source binding rejects path-like game ids before reading outside the game directory', () => {
  const root = fixture();
  const catalogPath = path.join(root, 'catalog.json');
  const catalog = JSON.parse(fs.readFileSync(catalogPath, 'utf8'));
  catalog.games[0].id = '../escape';
  fs.writeFileSync(catalogPath, JSON.stringify(catalog, null, 2) + '\n');
  assert.throws(() => deriveRegistry(root), /unsafe game id|source path escapes/);
});

test('--check semantics reject stale generated bytes', () => {
  const root = fixture();
  writeOrCheck(root, false);
  assert.doesNotThrow(() => writeOrCheck(root, true));
  fs.appendFileSync(path.join(root, 'registry/capabilities.jsonl'), '{"stale":true}\n');
  assert.throws(() => writeOrCheck(root, true), /stale generated registry/);
});
